### ISSUE TITLE
开源协议使用不规范

### ISSUE THREAD

**Issue by CrystalRays** [devsapp/agentcraft#17]
准备对agentcraft做二次开发，但是注意到虽然readme里写了使用apache2.0协议开源，但是项目并没有遵循apache协议放置LICENSE文件，也没有在每个代码文件头部放置版权声明。

**Comment by CrystalRays** [comment]
在你们注意到这个问题并解决之前，请允许我认为你们的apache2协议申明没有生效

**Comment by hanxie-crypto** [comment]
已经增加LICENE文件
