### ISSUE TITLE
前端用到的层缺少新加坡节点

### ISSUE THREAD

**Issue by moonfiendwill** [devsapp/agentcraft#25]
layers:
  #       - acs:fc:${vars.region}:official:layers/Nodejs18/versions/1
  #       - >-
  #         acs:fc:${vars.region}:1154600634854327:layers/agentcraft-frontend/versions/1
这两个层需要region : ap-southeast-1

**Comment by hanxie-crypto** [comment]
已添加 acs:fc:ap-southeast-1:1154600634854327:layers/agentcraft-frontend/versions/5 的层
