### ISSUE TITLE
 ChatGLM2-6b、ChatGLM3-6b

### ISSUE THREAD

**Issue by lichao370180184** [devsapp/agentcraft#8]
如何添加  其它的模型？部署完之后，基础模型里只有只有千问。。

**Comment by hanxie-crypto** [comment]
更新后已经可以支持 60+ 基础大语言模型，代理了 dashscope, zhipu, togetherai等平台的llm api，同时支持自己host llama2, chatglm3-6b， qwen-7b等到阿里云函数计算，后续会补充添加自定义模型的教程
